- name: Show Datacenter Location
  debug:
    var: datacenter
  when: datacenter is defined

- name: Show Run on Device
  ios_command:
    commands:
      - show run
  register: config

- name: get current configured ntp servers
  set_fact: _servers="{{ config.stdout[0] | regex_findall('^ntp server (\S+)', multiline=True) }}"

- name: remove old ntp servers
  ios_config:
    lines:
      - "no ntp server {{ item }}"
  with_items: "{{ _servers }}"
  when: remove_existing



- name: configure new NTP server 
  ios_config: 
    lines: 
      - ntp server {{ item }}
  with_items: "{{ ntp_server_list }}"

- name: configure new NTP server - Host Specific
  ios_config: 
    lines: 
      - ntp server {{ item }}
  with_items: "{{ host_ntp_server_list }}"
  when: host_ntp_server_list is defined